/*******************************************************************************
 * Copyright 2015 Esri
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 ******************************************************************************/
package com.esri.vehiclecommander.view;

import com.esri.core.geometry.Point;
import com.esri.core.geometry.SpatialReference;
import com.esri.core.map.Graphic;
import com.esri.militaryapps.controller.ChemLightController;
import com.esri.militaryapps.model.Geomessage;
import java.awt.Color;
import java.awt.Component;

/**
 * A JPanel that lets the user change the chem light's color or delete the chem light.
 */
public class ChemLightJPanel extends RoundedJPanel {
    
    private final ChemLightController chemLightController;
    private final Graphic chemLight;
    private final SpatialReference chemLightSR;
    
    private Component componentToHide = null;

    /**
     * Instantiates a ChemLightJPanel.
     * @param chemLightController the ChemLightController used to send messages to
     *        update and remove chem lights.
     * @param chemLight the chem light Graphic.
     * @param chemLightSpatialReference the spatial reference for the chem light
     *        Graphic's point geometry.
     */
    public ChemLightJPanel(
            ChemLightController chemLightController,
            Graphic chemLight,
            SpatialReference chemLightSpatialReference) {
        initComponents();
        
        this.chemLightController = chemLightController;
        this.chemLight = chemLight;
        this.chemLightSR = chemLightSpatialReference;
    }
    
    /**
     * Sets a component that will be hidden when a button is selected in this ChemLightJPanel.
     * One possible usage is to pass the component that contains this panel, so that
     * the containing component, and hence this panel, is hidden when the user clicks
     * a button.
     * @param componentToHide the component to hide.
     */
    public void setComponentToHide(Component componentToHide) {
        this.componentToHide = componentToHide;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_chemlight_red = new javax.swing.JButton();
        jButton_chemlight_yellow = new javax.swing.JButton();
        jButton_chemlight_green = new javax.swing.JButton();
        jButton_chemlight_blue = new javax.swing.JButton();
        jButton_chemlight_remove = new javax.swing.JButton();

        jButton_chemlight_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Red-Normal.png"))); // NOI18N
        jButton_chemlight_red.setBorderPainted(false);
        jButton_chemlight_red.setContentAreaFilled(false);
        jButton_chemlight_red.setFocusable(false);
        jButton_chemlight_red.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_chemlight_red.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_red.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_red.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_red.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Red-Pressed.png"))); // NOI18N
        jButton_chemlight_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chemlight_redActionPerformed(evt);
            }
        });

        jButton_chemlight_yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Yellow-Normal.png"))); // NOI18N
        jButton_chemlight_yellow.setBorderPainted(false);
        jButton_chemlight_yellow.setContentAreaFilled(false);
        jButton_chemlight_yellow.setFocusable(false);
        jButton_chemlight_yellow.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_chemlight_yellow.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_yellow.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_yellow.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_yellow.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Yellow-Pressed.png"))); // NOI18N
        jButton_chemlight_yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chemlight_yellowActionPerformed(evt);
            }
        });

        jButton_chemlight_green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Green-Normal.png"))); // NOI18N
        jButton_chemlight_green.setBorderPainted(false);
        jButton_chemlight_green.setContentAreaFilled(false);
        jButton_chemlight_green.setFocusable(false);
        jButton_chemlight_green.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_chemlight_green.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_green.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_green.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_green.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Green-Pressed.png"))); // NOI18N
        jButton_chemlight_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chemlight_greenActionPerformed(evt);
            }
        });

        jButton_chemlight_blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Blue-Normal.png"))); // NOI18N
        jButton_chemlight_blue.setBorderPainted(false);
        jButton_chemlight_blue.setContentAreaFilled(false);
        jButton_chemlight_blue.setFocusable(false);
        jButton_chemlight_blue.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_chemlight_blue.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_blue.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_blue.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_blue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/ChemLights-Blue-Pressed.png"))); // NOI18N
        jButton_chemlight_blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chemlight_blueActionPerformed(evt);
            }
        });

        jButton_chemlight_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/Discard-Normal.png"))); // NOI18N
        jButton_chemlight_remove.setBorderPainted(false);
        jButton_chemlight_remove.setContentAreaFilled(false);
        jButton_chemlight_remove.setFocusable(false);
        jButton_chemlight_remove.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_chemlight_remove.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_remove.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_remove.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_chemlight_remove.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esri/vehiclecommander/resources/Discard-Pressed.png"))); // NOI18N
        jButton_chemlight_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chemlight_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_chemlight_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_chemlight_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_chemlight_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_chemlight_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_chemlight_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_chemlight_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chemlight_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chemlight_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chemlight_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chemlight_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hideComponentToHide() {
        if (null != componentToHide) {
            componentToHide.setVisible(false);
        }
    }
    
    private void chemLightColorChangeClicked(final int rgbColor) {
        new Thread() {
            @Override
            public void run() {
                Point pt = (Point) chemLight.getGeometry();
                chemLightController.sendChemLight(pt.getX(), pt.getY(), chemLightSR.getID(),
                        rgbColor, (String) chemLight.getAttributeValue(Geomessage.ID_FIELD_NAME));
            }
        }.start();
        hideComponentToHide();
    }
    
    private void jButton_chemlight_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chemlight_redActionPerformed
        chemLightColorChangeClicked(Color.RED.getRGB());
    }//GEN-LAST:event_jButton_chemlight_redActionPerformed

    private void jButton_chemlight_yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chemlight_yellowActionPerformed
        chemLightColorChangeClicked(Color.YELLOW.getRGB());
    }//GEN-LAST:event_jButton_chemlight_yellowActionPerformed

    private void jButton_chemlight_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chemlight_greenActionPerformed
        chemLightColorChangeClicked(Color.GREEN.getRGB());
    }//GEN-LAST:event_jButton_chemlight_greenActionPerformed

    private void jButton_chemlight_blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chemlight_blueActionPerformed
        chemLightColorChangeClicked(Color.BLUE.getRGB());
    }//GEN-LAST:event_jButton_chemlight_blueActionPerformed

    private void jButton_chemlight_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chemlight_removeActionPerformed
        new Thread() {
            @Override
            public void run() {
                chemLightController.removeChemLight((String) chemLight.getAttributeValue(Geomessage.ID_FIELD_NAME));
            }
        }.start();
        hideComponentToHide();
    }//GEN-LAST:event_jButton_chemlight_removeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_chemlight_blue;
    private javax.swing.JButton jButton_chemlight_green;
    private javax.swing.JButton jButton_chemlight_red;
    private javax.swing.JButton jButton_chemlight_remove;
    private javax.swing.JButton jButton_chemlight_yellow;
    // End of variables declaration//GEN-END:variables
}
