define({
  root: {
    gpServiceTitle: "Geoprocessing Services Parameters",
    windDirectionTitle: "Wind Direction Parameters",
    facilitiesTitle: "Facilities Layer Parameters",
    demographicTitle: "Demographic Layer Parameters",
    chemicalGPService: "Chemical GP Service",
    placardGPService: "Placard GP Service",
    weatherStationGPService: "Weather Station GP Service",
    windDirectionLayer: "Wind Direction Layer",
    windDirectionField: "Wind Direction Field Name",
    stationNameField: "Station Field Name",
    dateTimeField: "Date Time Field Name",
    facilitiesLayer: "Facilities Map Service",
    demographicLayer: "Demographic Map Service",
    facilitiesFields: "Fields",
    facilitiesLabelField: "Label Field",
    demographicLabelField: "Label Field",
    demographicLabel: "Description",
    demographicMedia: "Media"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});
